version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_postgres_hw2
    environment:
      POSTGRES_DB: mydatabasehw2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data
volumes:
  my_db_volume: