spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyDatabaseHw6
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always


server:
  port: 8081
#debug: true