spring:
  application:
    name: HW2
  datasource:
    url: jdbc:postgresql://localhost:5432/MyDataBaseHw5
    username: admin
    password: admin
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
#debug: true